<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/m32/projects/colo/vis3d/static/models/crac_ph250.glb --root /models/ --types --printwidth 120 --precision 2
Author: ismadi (https://sketchfab.com/abgnokia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crah-ph250-down-flow-e28bb3bf4b1e4718bd3a65201a93b70c
Title: CRAH PH250 (DOWN FLOW)
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Material2: THREE.Mesh
      Material2_1: THREE.Mesh
      Material2_2: THREE.Mesh
      Material2_3: THREE.Mesh
      Material2_4: THREE.Mesh
      Material2_5: THREE.Mesh
    }
    materials: {
      edge_color575759255: THREE.LineBasicMaterial
      ['PEX-FACE.jpg']: THREE.MeshStandardMaterial
      ['SCREEN-6.jpg']: THREE.MeshStandardMaterial
      ['VERTIV-3.jpg']: THREE.MeshStandardMaterial
      ['CONT-TIANG.jpg']: THREE.MeshStandardMaterial
      edge_color128128128255: THREE.LineBasicMaterial
      ['0136_Charcoal']: THREE.MeshStandardMaterial
      ['CHROME-6.jpg']: THREE.MeshStandardMaterial
      edge_color000255: THREE.LineBasicMaterial
      edge_color174174171255: THREE.LineBasicMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/crac_ph250.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]}>
      <T.LineSegments geometry={gltf.nodes.Material4.geometry} material={gltf.materials.edge_color575759255} />
      <T.Mesh geometry={gltf.nodes.Material2.geometry} material={gltf.materials['PEX-FACE.jpg']} />
      <T.Mesh geometry={gltf.nodes.Material2_1.geometry} material={gltf.materials['SCREEN-6.jpg']} />
      <T.Mesh geometry={gltf.nodes.Material2_2.geometry} material={gltf.materials['VERTIV-3.jpg']} />
      <T.Mesh geometry={gltf.nodes.Material2_3.geometry} material={gltf.materials['CONT-TIANG.jpg']} />
      <T.LineSegments geometry={gltf.nodes.Material3.geometry} material={gltf.materials.edge_color128128128255} />
      <T.Mesh geometry={gltf.nodes.Material2_4.geometry} material={gltf.materials['0136_Charcoal']} />
      <T.Mesh geometry={gltf.nodes.Material2_5.geometry} material={gltf.materials['CHROME-6.jpg']} />
      <T.LineSegments geometry={gltf.nodes.Material2_6.geometry} material={gltf.materials.edge_color000255} />
      <T.LineSegments geometry={gltf.nodes.Material2_7.geometry} material={gltf.materials.edge_color174174171255} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
