<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/m32/projects/colo/vis3d/static/models/fence.glb --root /models/ --types --printwidth 120 --precision 2
Author: adventurer (https://sketchfab.com/ahmagh2e)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fence-51d87c04a1d346d2b9213c595b101c58
Title: Fence
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      base_base_0: THREE.Mesh
      tor_tor_0: THREE.Mesh
    }
    materials: {
      base: THREE.MeshStandardMaterial
      material: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/fence.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0.01}>
      <T.Mesh geometry={gltf.nodes.base_base_0.geometry} material={gltf.materials.base} position={[-0.1, 101.4, 0]} />
      <T.Mesh geometry={gltf.nodes.tor_tor_0.geometry} material={gltf.materials.material} position={[-0.1, 101.4, 0]} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
