<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/m32/projects/colo/vis3d/static/models/server_rack.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Server_Rack_1: THREE.Mesh
      Server_Rack_2: THREE.Mesh
    }
    materials: {
      Server: THREE.MeshStandardMaterial
      Server_AB: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/server_rack.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Server_Rack_1.geometry} material={gltf.materials.Server} />
    <T.Mesh geometry={gltf.nodes.Server_Rack_2.geometry} material={gltf.materials.Server_AB} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
