<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/m32/projects/colo/vis3d/static/models/VR3100.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      VR3100: THREE.Mesh
      Mesh001: THREE.Mesh
      Mesh001_1: THREE.Mesh
      VR3100_Grid: THREE.Mesh
    }
    materials: {
      BaseMaterials: THREE.MeshStandardMaterial
      VR3100_Decals: THREE.MeshStandardMaterial
      VR3100_Grid: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/VR3100.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.VR3100.geometry} material={gltf.materials.BaseMaterials} />
    <T.Mesh geometry={gltf.nodes.VR3100_Grid.geometry} material={gltf.materials.VR3100_Grid} />
    <T.Mesh geometry={gltf.nodes.Mesh001.geometry} material={gltf.materials.VR3100_Decals} />
    <T.Mesh geometry={gltf.nodes.Mesh001_1.geometry} material={gltf.materials.BaseMaterials} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
